jobs:
  include:
    - stage: 'Commit Today Json'
      script:
        - openssl aes-256-cbc -K $encrypted_a62f2225bf70_key -iv $encrypted_a62f2225bf70_iv -in key.enc -out ~/.ssh/id_rsa -d
        - chmod 600 ~/.ssh/id_rsa
        - git config --global user.email "yasutakekurita@gmail.com"
        - git config --global user.name "yakuri"
        - git clone --depth=50 --branch=master git@github.com:yakuri/covid19.git
        - cd covid19
        - curl https://covid19-japan-web-api.now.sh/api/v1/prefectures > data/prefectures_`date +"%Y%m%d"`.json
        - git add --all
        - git commit -m "by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
        - git push origin master
        - env TZ=JST-9 date
