# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron:  '*/15 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        git config --global user.email "yasutakekurita@gmail.com"
        git config --global user.name "yakuri"
        DATE=`env TZ=JST-9 date +"%Y%m%d"`
        DATETIME=`env TZ=JST-9 date +"%Y-%m-%dT%H:%M:%S+09:00"`
        COLON=":"
        echo "{\"date\" ${COLON} \"${DATETIME}\", \"data\" ${COLON}" > docs/data/prefectures_$DATE.json
        curl https://covid19-japan-web-api.now.sh/api/v1/prefectures >> docs/data/prefectures_$DATE.json
        echo } >> docs/data/prefectures_$DATE.json
        git add --all
        git commit -m "Update prefectures_$DATE.json"
